name: Semgrep

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Semgrep
        run: semgrep scan --config auto --error
